#location: /home/hedroed/.zshrc
# If you come from bash you might have to change your $PATH.
export TERM=xterm

fpat+=~/.zfunc

# Path to your oh-my-zsh installation.
export ZSH=/home/hedroed/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

ZSH_THEME="hedroed-bureau"
#ZSH_THEME="cobalt2"
#ZSH_THEME="agnoster"
#ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    docker
    sudo
    #command-not-found
    common-aliases
    nvm
    virtualenv
    emoji
    ssh-agent
    autojump
)


# Ssh Agent plugin
zstyle :omz:plugins:ssh-agent identities id_rsa #id_github

source $ZSH/oh-my-zsh.sh

# Fix docker completion
autoload -U compinit && compinit

# User configuration

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# history size
export SAVEHIST='1000000'
export HISTSIZE='1000000'

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

# User env preferences
export DEFAULT_USER="hedroed"
export EDITOR="vim"
export SUDO_EDITOR="vim"
export VISUAL="vim"

alias open='xdg-open'
alias ipa='ip a'
alias lf='ls -ltFhS --group-directories-first'

# Virtualenv wrapper
if [ -d ~/.virtualenvs ]; then
    export WORKON_HOME=~/.virtualenvs
    export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
    mkdir -p $WORKON_HOME
    source ~/.local/bin/virtualenvwrapper.sh
fi

export PATH=$PATH:~/Security/tools

# Haskell compiler
# export PATH=$PATH:/opt/ghc/bin

# Transfer.sh script
source ~/transfer.sh

# Android
#export ANDROID_HOME=/home/hedroed/android

# Go
export PATH=$PATH:~/go/bin

# Rust
export PATH=$PATH:~/.cargo/bin

# Dircolors
eval $(dircolors ~/.dir_colors)

function pdf() {
    file=$(mktemp)
    evince-thumbnailer -s 1000 $1 $file && kitty +kitten icat $file
}

# Guix
GUIX_PROFILE="/home/hedroed/.guix-profile"
. "$GUIX_PROFILE/etc/profile"

if [ -e /home/hedroed/.nix-profile/etc/profile.d/nix.sh ]; then . /home/hedroed/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
